import "./globals.css";

export const metadata = {
	title: "Mrenga Motors | Luxury car rentals",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
